"use strict";

$(document).ready(function() {
    "use strict";

//=====================================> SELECTORS


        var element = document.getElementsByTagName('h1');
        console.log(element);

        var element = $("h1"); // select tag
        console.log(element);

        var element = $("p"); // select class
        console.log(element);

        var element = $("#someDiv"); // select id
        var element = $("li, .paragraph"); // select combinations
        var element = $("*"); // select all

        console.log(element);

//=====================================> GETTING A VALUE

    var element = $("main"); // select tag
        console.log(element.html());



//=====================================> CHANGING A VALUE

    // HTML
        element.html("<h1>Canada</h1>");

    // Text =====>
        element.text("<h1>Texas</h1>");
    //or-->
        var mainText = "<h1>Canada</h1>";
        element.text(mainText);

    // single CSS property =====>
        element.css("border", "10px solid black");

    // multiple CSS properties =====>
        $('main').css({
            "background-color": "red",
            "color": "yellow"
        });

    $('main').css("background-color", "red").css("color", "yellow");

});




//
// //ajax code
// <!DOCTYPE html>
// <html>
// <head>
// <title>Orders</title>
// <link rel="shortcut icon" href="about:blank">
//
//     <style>
//
//     section {
//     background-color: cornsilk;
//     border: 2px solid black;
//     margin-bottom: 5px;
//     padding: 10px;
// }
// dt {
//     font-weight: bold;
// }
// dd {
//     text-decoration: underline;
// }
// </style>
//
// </head>
// <body>
//
// <h1>Current Orders</h1>
// <div id="orders">
//     <!-- This HTML should be dynamically generated by JS -->
// <section>
// <h3>Order #x</h3>
// <dl>
// <dt>Item Ordered</dt>
// <dd>Such and such item</dd>
// <dt>Ordered by</dt>
// <dd>Ordered by such and such</dd>
// </dl>
// </section>
// </div>
// <button id="update">Update w/Ajax</button>
//
// <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
//
//     <script>
//     $(document).ready(function() {
//         "use strict";
//
//         function makeRequestAndUpdatePage() {
//             var ajaxRequest = $.ajax("./data/orders.json");
//
//             ajaxRequest.done(function(data) {
//                 buildHTML(data);
//             });
//
//             ajaxRequest.fail(function(jqXhr, status) {
//                 console.log(status + " request failed");
//             });
//         }
//
//
//         //===============================>Step 2
//
//
//         function buildHTML(orders) {
//             var ordersHTML = "";
//
//             orders.forEach(function(order) {
//                 ordersHTML += "<section>";
//                 ordersHTML += "<h3>Order #" + order.orderNumber + "</h3>";
//                 ordersHTML += "<dl>";
//                 ordersHTML += "<dt>Item Ordered</dt>";
//                 ordersHTML += "<dd>" + order.itemOrdered + "</dd>";
//                 ordersHTML += "<dt>Ordered By</dt>";
//                 ordersHTML += "<dd>" + order.orderedBy + "</dd>";
//                 ordersHTML += "</section>";
//             });
//
//             $('#orders').html(ordersHTML);
//         }
//
//         $('#update').click(makeRequestAndUpdatePage);
//     });
//
// </script>
// </body>
// </html>